font_family FiraCode Nerd Font
font_size 18.0
shell /opt/homebrew/bin/fish

window_padding_width 5
background_opacity 0.98
background_blur 25

macos_option_as_alt yes
hide_window_decorations titlebar-only
mouse_hide_wait 0
enable_audio_bell no
scrollback_lines 20000
shell_integration enabled
copy_on_select clipboard
clipboard_control write-clipboard write-primary read-clipboard read-primary

cursor_shape beam
cursor_blink_interval 0
cursor_trail 1

tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge bottom

map cmd+enter new_window
map cmd+t new_tab
map cmd+w close_window
map cmd+shift+] next_tab
map cmd+shift+[ previous_tab
map cmd+k clear_terminal scroll active
map cmd+backspace send_text all \x15
map cmd+delete send_text all \x15

# TokyoNight Night
# include ~/.cache/wal/colors-kitty.conf
foreground #c0caf5
background #1a1b26
selection_foreground #1a1b26
selection_background #c0caf5
cursor #c0caf5
url_color #73daca

active_border_color #7aa2f7
inactive_border_color #414868
bell_border_color #e0af68
active_tab_foreground #1a1b26
active_tab_background #7aa2f7
inactive_tab_foreground #c0caf5
inactive_tab_background #414868

color0 #15161e
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #7aa2f7
color5 #bb9af7
color6 #7dcfff
color7 #a9b1d6
color8 #414868
color9 #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5
